### PR TITLE
Proper fix for protocol relative link absolutization

### LINKED ISSUE #25: Reader::findFeedLinks() failing with protocol-relative URLs
I've noticed a little bug on `Zend\Feed\Reader\Reader::findFeedLinks method`:

When a website is providing the feed URL as a 'protocol-relative' URL, the final URI returned by `Reader\FeedSet::absolutiseUri` method is in a invalid format.

Example:

The [Engadget](http://www.engadget.com) website feed URL is **//www.engadget.com/rss.xml** (is not started with **http://**, but with only **//**), so, when the Reader module prepare it to use, the URL returned is: **http://www.engadget.com/www.engadget.com/rss.xml**, and obviously when we try to read data from this URL, it fails.

```
<?php
$feedLinks = Zend\Feed\Reader\Reader::findFeedLinks('http://www.engadget.com');

echo $feedLinks->rss;
// Output: http://www.engadget.com/www.engadget.com/rss.xml
```

For now, I solved the problem by checking if the URL starts with **//** on `Reader\FeedSet::absolutiseUri` and prepending the protocol if it don't exists:

```
src/Reader/FeedSet.php:65
...

    protected function absolutiseUri($link, $uri = null)
    {
        /*
         * Fix: check if $link is a protocol-relative URL and prepend protocol to it
         */
        if (substr($link, 0, 2) == '//') {
            $link = 'http:' . $link;
        }

        $linkUri = Uri::factory($link);
        if (!$linkUri->isAbsolute() or !$linkUri->isValid()) {
            if ($uri !== null) {
                $uri = Uri::factory($uri);
...
```

Can you confirm this bug? Once confirmed, I can open a PR with this fix.

Thanks!

### PR DESCRIPTION
**Pull request by Xerkus**
Fixes #25
Proper fix for #2 

Test before fix:
```
1) ZendTest\Feed\Reader\FeedSetTest::testAbsolutiseUri with data set "protocol-relative" ('//example.com/feed', 'https://example.org', 'https://example.com/feed')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'https://example.com/feed'
+'https://example.org/example.com/feed'

test/Reader/FeedSetTest.php:36

2) ZendTest\Feed\Reader\FeedSetTest::testAbsolutiseUri with data set "protocol-relative-default" ('//example.com/feed', '//example.org')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://example.com/feed'
+'http://example.org/example.com/feed'

test/Reader/FeedSetTest.php:36
```

### CODE REVIEW

File: src/Reader/FeedSet.php [hunk 1]
```diff
@@ -68,21 +68,25 @@ protected function absolutiseUri($link, $uri = null)
         if (! $linkUri->isAbsolute() or ! $linkUri->isValid()) {
             if ($uri !== null) {
                 $uri = Uri::factory($uri);
-
+            }
+            if ($linkUri->getHost()) {
```
Comment (Ocramius) [inline src/Reader/FeedSet.php]: Can we move this block to a private method?

File: src/Reader/FeedSet.php [hunk 2]
```diff
@@ -68,21 +68,25 @@ protected function absolutiseUri($link, $uri = null)
...
                     ($uri->getScheme() ?: 'http'),
                     $uri->getHost(),
                     $this->canonicalizePath($link)
                 );
+            }
 
-                if (! Uri::factory($link)->isValid()) {
-                    $link = null;
-                }
+            if (! Uri::factory($link)->isValid()) {
```
Comment (Ocramius) [inline src/Reader/FeedSet.php]: Same here - can we move to aprivate method?

File: src/Reader/FeedSet.php [hunk 3]
```diff
@@ -68,21 +68,25 @@ protected function absolutiseUri($link, $uri = null)
         if (! $linkUri->isAbsolute() or ! $linkUri->isValid()) {
             if ($uri !== null) {
                 $uri = Uri::factory($uri);
-
+            }
+            if ($linkUri->getHost()) {
+                // protocol relative
+                $scheme = $uri && $uri->getScheme() ? $uri->getScheme() : 'http';
```
Comment (Ocramius) [inline src/Reader/FeedSet.php]: The code path where `$uri->getScheme()` is used is not tested.

Comment (Ocramius) [reply src/Reader/FeedSet.php]: Can you also avoid calling `$uri->getScheme()` twice?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: src/Reader/FeedSet.php [hunk 4]
```diff
@@ -65,29 +65,49 @@ public function addLinks(DOMNodeList $links, $uri)
...
-                }
-            }
+        if (! Uri::factory($link)->isValid()) {
+            return null;
         }
+
         return $link;
     }
 
+    private function resolveSchemeRelativeUri($link, $scheme)
```
Comment (Ocramius) [inline src/Reader/FeedSet.php]: To be added: docblock

File: src/Reader/FeedSet.php [hunk 5]
```diff
@@ -65,29 +65,49 @@ public function addLinks(DOMNodeList $links, $uri)
...
+    {
+        $link = ltrim($link, '/');
+        return sprintf('%s://%s', $scheme, $link);
+    }
+
+    private function resolveRelativeUri($link, $scheme, $host, $uriPath)
```
Comment (Ocramius) [inline src/Reader/FeedSet.php]: To be added: docblock

**Review by Ocramius — CHANGES_REQUESTED** [review]

**Review by Ocramius — APPROVED** [review]
